# Generated by Django 4.0 on 2022-02-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0003_remove_celebs_role_celebs_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebs',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
