# Generated by Django 4.0 on 2022-01-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='')),
                ('trailer', models.FileField(upload_to='')),
                ('running_time', models.CharField(max_length=255, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('release_date', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
