# Generated by Django 4.0 on 2022-01-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(upload_to='trailers/'),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebs.celebs')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebs.role')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(to='movie.Crew'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movie.Genre'),
        ),
    ]
