# Generated by Django 4.0 on 2022-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='uploads/posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(upload_to='uploads/trailers/'),
        ),
    ]
