# Generated by Django 4.0 on 2022-02-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_director_movie_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
